/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=e2e/wrangler.jsonc --include-runtime=false --env-interface=E2EFrontendEnv e2e/env.d.ts` (hash: 64912edf0b062098bd86f4ae7ed07a2e)
interface __BaseEnv_E2EFrontendEnv {
	ASSETS: Fetcher;
	API: Fetcher /* hslu-skill-tree-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./frontend");
	}
	interface Env extends __BaseEnv_E2EFrontendEnv {}
}
interface E2EFrontendEnv extends __BaseEnv_E2EFrontendEnv {}
