/* eslint-disable */
// generated by Wrangler by running `wrangler types --config=e2e/wrangler.jsonc --include-runtime=false --env-interface=E2EFrontendEnv e2e/env.d.ts` (hash: 315b548fb25b6a1d5ad6c7e6155c44f8)
interface __BaseEnv_E2EFrontendEnv {
	API: Fetcher /* hslu-skill-tree-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./frontend");
	}
	interface Env extends __BaseEnv_E2EFrontendEnv {}
}
interface E2EFrontendEnv extends __BaseEnv_E2EFrontendEnv {}
